pre-release-commit-message = "chore(release): release version {{version}}"
tag-message = "Release version {{version}}"
pre-release-hook = ["git-cliff", "--output", "CHANGELOG.md", "--tag", "v{{version}}"]
